config/routes.rb
Hbcuhacks::Application.routes.draw do
  resources :events
  resources :students

  match "/about" => 'pages#about'

  match "/atl" => redirect("http://startupsathbcus-atl.eventbrite.com/")
  match "/dc" => redirect("http://startupsathbcus-dc.eventbrite.com/")
  match "/morgan" => redirect("http://morganhackathon.eventbrite.com/")
  match "/signup" => redirect("https://docs.google.com/forms/d/1RD3lDULc2ypjS_D7XS6ugQPSLmG3mzNiB7aalqO53lw/viewform")
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  root :to => 'pages#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :company_url, :image_url, :name, :featured
  validates :company_url, presence: true
  validates :image_url, presence: true
  validates :name, presence: true
  has_many :sponsorships
  has_many :events, through: :sponsorships
  
  scope :featured, where(featured: true).limit(4)
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :address, :desc, :end_date, :prizes, :start_date, :title, :registration_url, :company_ids
  validates :title, presence: true
  validates :address, presence: true
  validates :start_date, presence: true

  has_many :sponsorships
  has_many :companies, through: :sponsorships
  scope :upcoming, lambda { where("start_date > ?", DateTime.now).order("start_date ASC").limit(3) }
end

app/models/sponsorship.rb
class Sponsorship < ActiveRecord::Base
  attr_accessible :company_id, :event_id
  belongs_to :company
  belongs_to :event
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :email, :first_name, :github_name, :graduation_month, :graduation_year, :last_name, :linkedin_url, :major, :mobile, :profile_pic, :testimonial
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @upcoming_events = Event.upcoming
    @companies = Company.featured
  end

  def about

  end
end

app/controllers/students_controller.rb
class StudentsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :prizes %><br />
    <%= f.text_area :prizes %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Desc</th>
    <th>Prizes</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.start_date %></td>
    <td><%= event.end_date %></td>
    <td><%= event.desc %></td>
    <td><%= event.prizes %></td>
    <td><%= event.address %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.slim
section#subintro
  .jumbotron.subhead#overview
    .container
      .row
        .span8
          h3 =@event.title
section#maincontent
  .container
    .row
      .span4
        aside
          .widget
            h4.heading-success Event Details
            ul.project-detal
              li
                label
                  | Start : 
                = time_tag @event.start_date, format: '%A, %B %e, %Y %l:%M %p'
              - if @event.end_date
                li
                  label
                    | End : 
                  = time_tag @event.end_date, format: '%A, %B %e, %Y %l:%M %p'
              - if @event.address
                li
                  label
                    | Address : 
                  = @event.address.gsub(/\n/, '<br/>').html_safe
          - if @event.prizes
            .widget
              h4.heading-success Prizes
              ul.project-details
                li
                  = @event.prizes.gsub(/\n/, '<br/>').html_safe

      .span8
        article
          .tooltip-demo.headline
            h4
              = @event.title
          .clearfix
          = @event.desc.gsub(/\n/, '<br/>').html_safe
          - if @event.registration_url
            p style="margin-top:20px"
              a.btn.btn-large.btn-success href="#{@event.registration_url}" Register for Event
          - if @event.companies.any?
            .span8
              .row
                .divider
              .row
                h5 Sponsoring Companies
                - @event.companies.each do |company|
                  .span2
                    = image_tag company.image_url
            
		

app/views/layouts/application.html.slim
doctype html
html
  head
    title HBCUHacks
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    header
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            .brand.logo
              = link_to((image_tag "logo-final-250px.png"), "/")
            div style="float:right;margin-top:15px;margin-right:30px;"
              a.btn.btn-primary.btn-large href="/signup" target="blank" Bring HBCUHacks to Your School
    = yield
    footer.footer
      .verybottom
        .container
          .row
            center
              em
                | HBCUHacks is a program of 
                a href="http://www.blackfounders.com" target="blank"
                  | Black Founders
                | . Our mission is to increase the number of black entrepreneurs in tech. Questions? 
                a href="mailto:founders@blackfounders.com?subject=HBCUHacks%20Question"
                  | Email us!

app/views/pages/about.html.slim
h2 style="border-bottom:1px solid #EEE" About
| HBCU Hacks is a program by 
= link_to "Black Founders", "http://www.blackfounders.com"
|  that hosts hackathons at Historically Black Colleges and Universities (HBCU).
  The goal of the program is to introduce students to tech entrepreneurship and hacking
  by building mobile and web apps in a short intense duration, (typically 24 to 48 hours).
  Students participating in the hackathons have the opportunity to meet and work with mentors
  from tech startups. At the end of each hackathon, students will have completed and built a 
  mobile or web app. Any student, (regardless of major), enrolled in any undergraduate or
  graduate program can participate in the hackathons. 
p
  br
  | For more information or sponsorship opportunities please email us at 
  a href="mailto:founders@blackfounders.com" founders@blackfounders.com

p
  h3 Press
  ul
    li 
      a href="http://www.blackenterprise.com/technology/black-founders%E2%80%99-hbcu-hackathon-tour-exposes-students-to-the-art-of-hacking/" target="blank"
        | Featured in Black Enterprise Black Founders HBCU Hackathon Tour exposes students to the Art of Hacking
    li
      a href="http://www.drurly.com/blog/2013/02/10/black-founders-hackathon-my-experience/" target="blank"
        | Black Founders Hackathon - My Experience by Dru Riley

app/views/pages/index.html.slim
section#headline style="max-width:100%;height:150px;background:#f5f5f5;"
  .container
    .row
      .span12
        .tagline
          .row
            .span9
              .tagline_text 
                h2 Hackathons hosted at Historically Black Colleges and Universities
            .span3
              .btn-toolbar.cta
                a.btn.btn-large.btn-success href=signup_path Sign up
                a.btn.btn-large.btn-danger href="mailto:founders@blackfounders.com?subject=HBCUHack%20Sponsorship" Sponsor

.jumbotron.masthead style="margin-top:20px"
  .container
    .row
      .span12
        #slider.nivoSlider
          img src="/assets/hbcu_hack_auc_1.jpg" data-thumb="/assets/hbcu_hack_auc_1.jpg" alt=""
          img src="/assets/hbcu_hack_auc_2.jpg" data-thumb="/assets/hbcu_hack_auc_2.jpg" alt="" data-transition="slideInLeft"
          img src="/assets/hbcu_hack_auc_3.jpg" data-thumb="/assets/hbcu_hack_auc_3.jpg" alt="" data-transition="slideInLeft"

#maincontent style="margin-top:20px"
  .container
    .row
      .span7.tagline_text
		  h2 What is a hackathon?
		  | A hackathon is an event where individuals collaborate in a short and intense time period
			(typically 24 to 72 hours) to build a mobile or web application. A typical HBCUHack lasts for about
			24 hours. During the event, students form teams and work on an idea with a goal of building a web or mobile app.  
		  br
		  br
		  h2 What if I don't know how to code?
		  | Come anyway! Students from all majors are encouraged to attend and bring only an idea and a laptop. Programming 
			experience is not required, but familiarity with basic programming concepts is 
			helpful or joining a team with a student programmer is encouraged. Mentors will also available during the event to help you build your app. Besides, having a team with diverse backgrounds helps. We've noticed that our past winners are often teams that are made up of diverse majors. (ie: computer science, business, journalism, psychology).
		  br
		  br
		  h2 What's an HBCUHack really like?
		  | Read 
		  a href="http://www.drurly.com/blog/2013/02/10/black-founders-hackathon-my-experience/"
			| HBCUHacks - My Experience
		  | . It's a blog post by Dru Riley who attended the very first HBCUHack in Atlanta, GA. 
          
      .span5.upcoming_events
        h2 Upcoming HBCUHacks
		ul
          - if @upcoming_events != []
            - @upcoming_events.each do |event|
			  li
				div.event_date
				  = time_tag event.start_date, format: '%b %d'
				div.event_details
				  - if event.logo_url != ''
				    div.event_details_logo
					  a.event_link href=event_path(event.id)
					    = image_tag event.logo_url
				  - else
					|
				  div.event_details_location
					a.event_link href=event_path(event.id)
					  | #{event.title}
					br
					| #{event.address.gsub("\n", "<br />").html_safe} 
				  div.event_details_signup
					a.btn.btn-success href=signup_path
					  |  Sign up
          - else
            li TBA

.container
  .row
    .span12
      .divider
  - if @companies != []      
    .row
      .span12
        center
          h2 Cool Companies Working With Us
    .row
      - @companies.each do |company|
        .span3
          a href=company.company_url
            = image_tag company.image_url

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :profile_pic %><br />
    <%= f.text_field :profile_pic %>
  </div>
  <div class="field">
    <%= f.label :graduation_month %><br />
    <%= f.text_field :graduation_month %>
  </div>
  <div class="field">
    <%= f.label :graduation_year %><br />
    <%= f.number_field :graduation_year %>
  </div>
  <div class="field">
    <%= f.label :major %><br />
    <%= f.text_field :major %>
  </div>
  <div class="field">
    <%= f.label :linkedin_url %><br />
    <%= f.text_field :linkedin_url %>
  </div>
  <div class="field">
    <%= f.label :github_name %><br />
    <%= f.text_field :github_name %>
  </div>
  <div class="field">
    <%= f.label :testimonial %><br />
    <%= f.text_area :testimonial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Mobile</th>
    <th>Email</th>
    <th>Profile pic</th>
    <th>Graduation month</th>
    <th>Graduation year</th>
    <th>Major</th>
    <th>Linkedin url</th>
    <th>Github name</th>
    <th>Testimonial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.first_name %></td>
    <td><%= student.last_name %></td>
    <td><%= student.mobile %></td>
    <td><%= student.email %></td>
    <td><%= student.profile_pic %></td>
    <td><%= student.graduation_month %></td>
    <td><%= student.graduation_year %></td>
    <td><%= student.major %></td>
    <td><%= student.linkedin_url %></td>
    <td><%= student.github_name %></td>
    <td><%= student.testimonial %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @student.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @student.last_name %>
</p>

<p>
  <b>Mobile:</b>
  <%= @student.mobile %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>

<p>
  <b>Profile pic:</b>
  <%= @student.profile_pic %>
</p>

<p>
  <b>Graduation month:</b>
  <%= @student.graduation_month %>
</p>

<p>
  <b>Graduation year:</b>
  <%= @student.graduation_year %>
</p>

<p>
  <b>Major:</b>
  <%= @student.major %>
</p>

<p>
  <b>Linkedin url:</b>
  <%= @student.linkedin_url %>
</p>

<p>
  <b>Github name:</b>
  <%= @student.github_name %>
</p>

<p>
  <b>Testimonial:</b>
  <%= @student.testimonial %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>